[project]
name = "GardenAI"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "apscheduler",
    "deepagents>=0.3.5",
    "faiss-cpu",
    "fastmcp",
    "langchain",
    "langchain-anthropic",
    "langchain-core",
    "langchain-mcp-adapters",
    "langchain-openai",
    "langfuse",
    "langgraph",
    "lmdb",
    "loguru",
    "mem0ai",
    "numpy",
    "opuslib_next",
    "pillow>=10.0.0",
    "pydantic",
    "python-dotenv",
    "pyyaml>=6.0.0",
    "pyzmq",
    "redis",
    "requests",
    "rich>=13.0.0",
    "typing-extensions",
    "websockets",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = { find = { where = ["."], include = [
    "yard*"
] } }
